blanks_around_headings:
  lines_below: 0
ul_style: { style: sublist }
# not autofixable
ol-prefix: { style: ordered }
line-length:
  tables: false
  code_blocks: false
no-inline-html:
  allowed_elements: [img, details, summary, kbd, a, br]

#─────────────────────────────────────────────────────────────────────────────
# DISABLED
ul-indent: false # not compatible with using tabs
no-hard-tabs: false # taken care of by editorconfig
blanks-around-lists: false # space waster
first-line-heading: false # e.g., ignore-comments
no-emphasis-as-heading: false # sometimes useful
