[selene]
base = "luajit"
name = "vim"

[vim]
any = true

[before_each.args]
any = true
[it]
any = true
[describe]
any = true
[assert]
any = true

[jit]
any = true

[a]
any = true

[[describe.args]]
type = "string"

[[describe.args]]
type = "function"
