[alias]
b = "build"
r = "run"
t = "test"
c = "check"
R = "run --release"
rx = "R --example --recursions"
sx = ["run", "--release", "--", "\"command_list\""]

[env]
WORD_LSP_NAME = "wordlsp"
PATH = "$PATH"
CACHE = "$HOME/.cache/$WORD_LSP_NAME"
TEMPD = "$HOME/.tm/$WORD_LSP_NAME"
DATAD = "$HOME/.local/share/$WORD_LSP_NAME"
STATE = "$HOME/.local/state/$WORD_LSP_NAME"
CONFD = "$HOME/.config/$WORD_LSP_NAME"

[cargo-new]
vcs = "git"
