name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: word.lua
          extra-files: |
            README.md
            lua/word/util/version.lua

      - uses: actions/checkout@v4

      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          tag: stable
          message: "Stable release: ${{ steps.release.outputs.tag_name }}"
          force_push_tag: true
